[package]
name = "airclaw_starknet"
version = "0.1.0"
edition = "2024_07"

[features]
deprecated_legacy_map = []

[dependencies]
starknet = "2.8.0"

[[target.starknet-contract]]
sierra = true
casm = true
